ARG SDK_TAG=bcm27xx-bcm2712
FROM openwrt/sdk:${SDK_TAG}

USER buildbot
WORKDIR /builder

# Copy build scripts
COPY --chown=buildbot:buildbot scripts /builder/build-scripts
RUN chmod +x /builder/build-scripts/*.sh

# Default command
ENTRYPOINT ["/builder/build-scripts/local-build.sh"]
